### ISSUE TITLE
Use second dominent colour, when dominent colour is excluded

### ISSUE THREAD

**Issue by smth** [briangonzalez/jquery.adaptive-backgrounds.js#40]
I was expecting this to behave as the title described. Is it intentional that it doesn't?

For example, currently, if you have a red circle in a white square, with white being the dominant colour. You `exclude` white, then your background is set to black. If you also `exclude` black, your background is set to `rgb()`. I think it would make more sense if the background was set to red, once white has been excluded.

Edit: I'm guessing this is a bug, because I've noticed that when adding a 2px (red) border to the image I described above, it behaves as I originally expected.

**Comment by AlfredJKwack** [comment]
@smth I think the issue is with the underlying library [(RGBaster.js)](https://github.com/briangonzalez/rgbaster.js) which does the color calculations. It seems to not be doing what it should when it returns colors.

Adaptive-backgrounds blindly uses the input from rgbaster

`97           $parent.css({ backgroundColor: data.color }); `

Where data.color comes from:

`77         $this.on( EVENT_CF, function(ev, data){ `

and

```
53           RGBaster.colors(img, { 
54             paletteSize: 20, 
55             exclude: opts.exclude, 
56             success: function(colors) { 
57               $this.attr(DATA_COLOR, colors.dominant); 
58               $this.trigger(EVENT_CF, { color: colors.dominant, palette: colors.palette }); 
59             } 
60           });
``` 

Based on this it seems to me that you may want to raise the case in [RGBaster.js](https://github.com/briangonzalez/rgbaster.js) instead.

Another, more involved option, would be to replace [rgbaster.js](https://github.com/briangonzalez/rgbaster.js) with something else. You may want to look at [Lokesh's Color-Thief](https://github.com/lokesh/color-thief/) for that. Putting in this library at the right spots seems pretty straitforward.

**Comment by AlfredJKwack** [comment]
This should now be fixed. 

As noted previously , there was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.
